#include "../Dependencies/GLEW/include/GL/glew.h"

namespace GI {
	enum class BlendFunc {
		ZERO = GL_ZERO,
		ONE = GL_ONE,
		SRC_COLOUR = GL_SRC_COLOR,
		ONE_MINUS_SRC_COLOUR = GL_ONE_MINUS_SRC_COLOR,
		DST_COLOUR = GL_DST_COLOR,
		ONE_MINUS_DST_COLOUR = GL_ONE_MINUS_DST_COLOR,
		SRC_ALPHA = GL_SRC_ALPHA,
		ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
		DST_ALPHA = GL_DST_ALPHA,
		ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
		CONSTANT_COLOUR = GL_CONSTANT_COLOR,
		ONE_MINUS_CONSTANT_COLOUR = GL_ONE_MINUS_CONSTANT_COLOR,
		CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
		ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
		SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE
	};
	enum class FBO {
		COLOUR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
		DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT,
		STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT,
		DEPTH_AND_STENCIL_ATTACHMENT = GL_DEPTH_STENCIL_ATTACHMENT
	};
	namespace Texture {
		enum class Data {
			UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
			UNSIGNED_INT_24_8 = GL_UNSIGNED_INT_24_8
		};
		enum class Format {
			RGBA = GL_RGBA,
			DEPTH_STENCIL = GL_DEPTH_STENCIL
		};
		enum class IFormat {
			RGBA8 = GL_RGBA8,
			DEPTH24_STENCIL8 = GL_DEPTH24_STENCIL8
		};
		enum class Type {
			TEXTURE_1D = GL_TEXTURE_1D,
			TEXTURE_2D = GL_TEXTURE_2D,
			TEXTURE_3D = GL_TEXTURE_3D,
			TEXTURE_CUBE_MAP = GL_TEXTURE_CUBE_MAP
		};
		enum class Wrap {
			CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
			MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
			REPEAT = GL_REPEAT
		};
		enum class Mag {
			NEAREST = GL_NEAREST,
			LINEAR = GL_LINEAR
		};
		enum class Min {
			NEAREST = GL_NEAREST,
			LINEAR = GL_LINEAR,
			NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
			LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
			NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
			LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR
		};
	}

}